# Generated by Django 4.1 on 2022-08-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.TextField(verbose_name='Sorğu nömrəsi')),
                ('user_id', models.TextField(verbose_name='Müştəri İD')),
                ('datetime', models.DateTimeField(verbose_name='Təklifin qüvvədə olduğu müddət')),
                ('valyuta', models.CharField(max_length=10, verbose_name='Valyuta')),
                ('miqdar', models.CharField(max_length=10, verbose_name='Miqdar')),
                ('price', models.CharField(max_length=10, verbose_name='Vahidin qiyməti')),
                ('edv_degree', models.TextField(verbose_name='ƏDV drərəcəsi')),
                ('edv_price', models.CharField(max_length=10, verbose_name='ƏDV məbləği')),
                ('payment_terms', models.TextField(verbose_name='Ödəniş şərti')),
                ('bank_account', models.CharField(max_length=10, verbose_name='Bank hesabı')),
                ('discount', models.CharField(max_length=10, verbose_name='Endirim')),
                ('delivery_condition', models.TextField(verbose_name='Çatdırılma şərti')),
                ('country', models.TextField(verbose_name='Ölkə')),
                ('city', models.TextField(verbose_name='Şəhər')),
                ('location', models.TextField(verbose_name='Ünvan')),
                ('zipcode', models.TextField(verbose_name='Zip kod')),
                ('delivery_date', models.DateTimeField(verbose_name='Çatdırılma tarixi')),
                ('delivery_cost', models.CharField(max_length=10, verbose_name='Çatdırıl xərci')),
            ],
        ),
    ]
