# Generated by Django 4.1 on 2022-08-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='bank_account',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Bank hesabı'),
        ),
        migrations.AlterField(
            model_name='form',
            name='city',
            field=models.TextField(blank=True, null=True, verbose_name='Şəhər'),
        ),
        migrations.AlterField(
            model_name='form',
            name='country',
            field=models.TextField(blank=True, null=True, verbose_name='Ölkə'),
        ),
        migrations.AlterField(
            model_name='form',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Təklifin qüvvədə olduğu müddət'),
        ),
        migrations.AlterField(
            model_name='form',
            name='delivery_condition',
            field=models.TextField(blank=True, null=True, verbose_name='Çatdırılma şərti'),
        ),
        migrations.AlterField(
            model_name='form',
            name='delivery_cost',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Çatdırılma xərci'),
        ),
        migrations.AlterField(
            model_name='form',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Çatdırılma tarixi'),
        ),
        migrations.AlterField(
            model_name='form',
            name='discount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Endirim'),
        ),
        migrations.AlterField(
            model_name='form',
            name='edv_degree',
            field=models.TextField(blank=True, null=True, verbose_name='ƏDV drərəcəsi'),
        ),
        migrations.AlterField(
            model_name='form',
            name='edv_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ƏDV məbləği'),
        ),
        migrations.AlterField(
            model_name='form',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='form',
            name='miqdar',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Miqdar'),
        ),
        migrations.AlterField(
            model_name='form',
            name='payment_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Ödəniş şərti'),
        ),
        migrations.AlterField(
            model_name='form',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Vahidin qiyməti'),
        ),
        migrations.AlterField(
            model_name='form',
            name='request_number',
            field=models.TextField(blank=True, null=True, verbose_name='Sorğu nömrəsi'),
        ),
        migrations.AlterField(
            model_name='form',
            name='user_id',
            field=models.TextField(blank=True, null=True, verbose_name='Müştəri İD'),
        ),
        migrations.AlterField(
            model_name='form',
            name='valyuta',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='form',
            name='zipcode',
            field=models.TextField(blank=True, null=True, verbose_name='Zip kod'),
        ),
    ]
