# Generated by Django 4.0.5 on 2022-08-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_form_bank_account_alter_form_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='request_number',
        ),
        migrations.AddField(
            model_name='form',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
