# Generated by Django 4.0.5 on 2022-08-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_form_request_number_form_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='color',
        ),
        migrations.AddField(
            model_name='form',
            name='request_number',
            field=models.CharField(blank=True, choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6, null=True, verbose_name='Sorğu nömrəsi'),
        ),
    ]
