# Generated by Django 4.0.5 on 2022-08-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_form_request_number_alter_form_valyuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='delivery_condition',
            field=models.TextField(blank=True, choices=[('exw', 'EXW'), ('fca', 'FCA'), ('fob', 'FOB'), ('cif', 'CIF')], default='fca', max_length=4, null=True, verbose_name='Çatdırılma şərti'),
        ),
    ]
