# Generated by Django 4.0.5 on 2022-08-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_form_delivery_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='type_transport',
            field=models.CharField(blank=True, choices=[('avtomobil', 'AVTOMOBIL'), ('dəmir yolu', 'DƏMİR YOLU'), ('dəniz', 'DƏNİZ'), ('hava', 'HAVA')], default='avtomobil', max_length=10, null=True, verbose_name='Çatdırılma xərci'),
        ),
        migrations.AlterField(
            model_name='form',
            name='discount',
            field=models.CharField(blank=True, choices=[('var', 'VAR'), ('yoxdur', 'YOXDUR')], default='var', max_length=10, null=True, verbose_name='Endirim'),
        ),
        migrations.AlterField(
            model_name='form',
            name='valyuta',
            field=models.CharField(blank=True, choices=[('azn', 'AZN'), ('usd', 'USD'), ('eur', 'EUR'), ('try', 'TRY'), ('rub', 'RUB')], default='azn', max_length=10, null=True, verbose_name='Valyuta'),
        ),
    ]
