# Generated by Django 4.0.5 on 2022-08-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_form_type_transport_alter_form_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='payment_terms',
            field=models.TextField(blank=True, choices=[('öncədən ödəniş', 'ÖNCƏDƏN ÖDƏNİŞ'), ('konsiqnasiya', 'KONSİQNASİYA')], default='konsiqnasiya', max_length=14, null=True, verbose_name='Ödəniş şərti'),
        ),
        migrations.AlterField(
            model_name='form',
            name='type_transport',
            field=models.CharField(blank=True, choices=[('avtomobil', 'AVTOMOBİL'), ('dəmir yolu', 'DƏMİR YOLU'), ('dəniz', 'DƏNİZ'), ('hava', 'HAVA')], default='avtomobil', max_length=10, null=True, verbose_name='Çatdırılma xərci'),
        ),
    ]
