# Generated by Django 4.0.5 on 2022-08-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_form_payment_terms_alter_form_type_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='product',
            field=models.CharField(blank=True, choices=[('televizor', 'TELEVİZOR'), ('divan', 'DİVAN'), ('kitab', 'KİTAB'), ('deftər', 'DƏFTƏR')], default='kitab', max_length=20, null=True, verbose_name='Məhsul'),
        ),
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
