# Generated by Django 4.0.5 on 2022-08-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_form_product_form_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='tesdiq',
            field=models.BooleanField(default=False, verbose_name='Təsdiq gözlənilir'),
        ),
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Qaralama'),
        ),
    ]
