# Generated by Django 4.0.5 on 2022-08-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_form_tesdiq_alter_form_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(blank=True, max_length=30, null=True, verbose_name='Məhsul')),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='product',
        ),
        migrations.AddField(
            model_name='form',
            name='product',
            field=models.ManyToManyField(to='post.product'),
        ),
    ]
