# Generated by Django 4.0.5 on 2022-08-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_product_remove_form_product_form_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='user_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Müştəri İD'),
        ),
    ]
