# Generated by Django 4.0.5 on 2022-08-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_form_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='edv_degree',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ƏDV drərəcəsi'),
        ),
    ]
