# Generated by Django 4.0.5 on 2022-08-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_form_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='product',
        ),
        migrations.AddField(
            model_name='form',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mehsul', to='post.product', verbose_name='Məhsul'),
        ),
    ]
